repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        args: ['-S', '-l 120']
